version: '3'
services:
  # フロントエンド
  frontend:
    build: 
      context: ./frontend
      dockerfile: ./view/Dockerfile
    container_name: "fronend"
    volumes:
      - ./frontend/view:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
  # バックエンド
  backend:
    build: 
      context: ./backend
      dockerfile: ./build/Dockerfile
    container_name: "backend"
    image: "golang:1.21-alpine"
    volumes:
      - ./backend:/go/src/solution_develop/
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
  # DB
  my_sql:
    build: ./db
    platform: linux/amd64
    image: mysql:8.0.29
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      TZ: Asia/Tokyo #time-zone 指定.日本時間(東京)に設定 
    volumes:
      - ./db/data:/var/lib/mysql
